### ISSUE TITLE
[iOS] setLoggingEnabled logs only visible via XCode

### ISSUE THREAD

**Issue by flodaniel** [mixpanel/mixpanel-flutter#109]
When calling `setLoggingEnabled(true)` on the mixpanel instance, the debuggin logs are only visible when the app is directly built in xcode. I am using vscode and the logs are not visible in the `Debug Console`.

I am not 100% sure if this is a configuration setting in vscode, but as this usually works with other libraries out of the box, i would expect an internal "issue".

**Comment by zihejia** [comment]
hi @flodaniel , the log is only available in the Xcode at the moment.
