### ISSUE TITLE
Add compatibility with AGP 8 (Android Gradle Plugin)

### ISSUE THREAD

**Issue by biklas7** [mixpanel/mixpanel-flutter#111]
Android Flutter plugins should add `namespace` under `android` inside the build configuration for the app.
Something like [this](https://github.com/fluttercommunity/plus_plugins/pull/1704/files).

Also check official android documentation [here](https://developer.android.com/build/publish-library/prep-lib-release#choose-namespace).

**Comment by crobinsonpicdmo** [comment]
Need this too, any ETA?

**Comment by davidmigloz** [comment]
@zihejia any chances to get #123 or #124 merged soon?
This is a blocking issue that prevents apps that depend on `mixpanel_flutter` to migrate to AGP 8.

Thanks!

**Comment by jimmy0251** [comment]
Android builds failing because of this. Is this going to get merged soon?

**Comment by xleon** [comment]
This is a big blocker.

**Comment by asgeirenersen** [comment]
Waiting anxiously for this.

**Comment by ziadsarour** [comment]
Waiting for this too.
This is the only dependency that is blocking me :/

**Comment by davidmigloz** [comment]
I contacted support, and they replied:


> Hi David, 
> 
> I got an update from the Engineering team who shared that they will need to test the PR before approving. I should have another update by late next week, I just wanted to let you know that they are planning on reviewing it soon.

**Comment by derekpitts28** [comment]
Bump to this, need this support for AGP 8.0+

**Comment by davidmigloz** [comment]
This issue is now fixed in v2.3.0 🚀
https://github.com/mixpanel/mixpanel-flutter/releases/tag/v2.3.0
