### ISSUE TITLE
docs: include information that simulators are not supported

### ISSUE THREAD

**Issue by danallen88** [mixpanel/mixpanel-flutter#112]
It would be helpful to point out in the README that the simulator is not a supported platform and will not send data to Mixpanel (at least on iOS).

**Comment by zihejia** [comment]
hi @danallen88 , the simulator should work just fine, are you sure your simulator has internet access?

**Comment by danallen88** [comment]
Ah, I wonder if the traffic is being blocked by an aggressive corporate firewall. My apologies, I'll close the issue.
