### ISSUE TITLE
Email is undefined on Users dashboard 

### ISSUE THREAD

**Issue by tomasbaran** [mixpanel/mixpanel-flutter#119]
This is how I'm setting Email ($email) property: `MixpanelService.mixpanel?.getPeople().set('\$email', email);` and it shows correctly in the user profile section:
<img width="392" alt="Screenshot 2023-10-25 at 8 05 30 p m" src="https://github.com/mixpanel/mixpanel-flutter/assets/25743901/43d66a3d-54de-4cd7-94d3-fa98c0c69ab1">

but not in the dashboard:
<img width="667" alt="Screenshot 2023-10-25 at 8 06 06 p m" src="https://github.com/mixpanel/mixpanel-flutter/assets/25743901/88a491a5-a96b-4d71-bf7a-51602a04eab0">

**Comment by zihejia** [comment]
I'm closing this one for now as this should not be the SDK issue.
