### ISSUE TITLE
user properties do not get updated

### ISSUE THREAD

**Issue by tomasbaran** [mixpanel/mixpanel-flutter#120]
This is how I set it and it logs them successfully, yet it doesn't get through even after 30 minutes. 

``` dart
try {
        MixpanelService.mixpanel?.getPeople().set('last_used', DateTimeUtils.mixpanelNow());
        MixpanelService.mixpanel?.getPeople().set('active_period', activePeriod);
        MixpanelService.mixpanel?.getPeople().set('completed_todoes_per_day', double.parse(completedTodoesPerDay.toStringAsFixed(0)));
        log('mixpanel updated: ${DateTimeUtils.mixpanelNow()}, $activePeriod, ${completedTodoesPerDay.toStringAsFixed(0)}');
      } catch (e) {
        log('\x1B[31mError #3[adding stat]: $e\x1B[0m');
        Logger(printer: PrettyPrinter(colors: false)).e('\x1B[31mError #3[updating mixpanel]: $e\x1B[0m');
      }
```

Events do come through, so do the user properties but only sporadically.

**Comment by smn-snkl** [comment]
We are having the same issues. Did you find any solution?

**Comment by tomasbaran** [comment]
unfortunately, not.

**Comment by tomasbaran** [comment]
is mixpanel dead for flutter or for any platform? It seems it's not working correctly and noone is responding to issues.

**Comment by tomasbaran** [comment]
what would be a good alternative? In the past firebase analytics didn't work as precisely as mixpanel, could it be the other way around this year?

**Comment by tomasbaran** [comment]
@smn-snkl actually my issue was divided into two seperate issues:

1. one is still being open: I reported it seperataly now here: https://github.com/mixpanel/mixpanel-flutter/issues/121 
2. as for the regular userProperty (getPeople().set()), it was a bug on my side: I forgot to add ` MixpanelService.mixpanel?.identify(authService.uid!);` for already signed in users. Hope it helps.
