### ISSUE TITLE
Add support for js 0.7.0

### ISSUE THREAD

**Issue by zacherygentry** [mixpanel/mixpanel-flutter#130]
This package currently depends on js ^0.6.3. It should be bumped to support the latest js ^0.7.0 version

**Comment by Fudal** [comment]
@zihejia @jaredmixpanel Do you continue to support this library? We are waiting for a dependency update, and there has been no update for 3 months, not even such a simple thing as bumping up the versions of the internal libraries. This blocks us from updating other libraries in our own project.

**Comment by zihejia** [comment]
hi @Fudal , we apologize for the delay and any inconvenience it may have caused, we will do a release by early next week, which will also include some additional fixes.

**Comment by danbeechbloom** [comment]
@zihejia any updates for the JS version bump please? It's blocking updates to other packages that need to be updated ASAP.

**Comment by zihejia** [comment]
It's included in version 2.3.0! Thanks for your patience!
