### ISSUE TITLE
What will happen if the data can not be tracked due to the network connection?

### ISSUE THREAD

**Issue by thphuc** [mixpanel/mixpanel-flutter#135]
Here is the flow of the application:
1. The app calls an API to our backend to create a user (an account) OR to log in with an existing account. If successful, the app will receive a user_id
2. The app then calls `.identify(<user_id>)` to send the user id to Mixpanel

Question: If the network connection is not working right after step 1 and before step 2, what will happen? Will Mixpanel retry the `.identify(<user_id>)` later when the network is working again?

If not, the user will not be tracked on Mixpanel?

**Comment by zihejia** [comment]
hi @thphuc , Mixpanel will retry the events and nothing will be lost.
