### ISSUE TITLE
Please add Windows support

### ISSUE THREAD

**Issue by dickverweij** [mixpanel/mixpanel-flutter#137]
Our flutter app runs on Web, IOS, Android and Windows. We use mixpanel for IOS and Android and it is working fine!

Is there a possibility to get mixpanel stats on the windows client?

**Comment by zihejia** [comment]
hi @dickverweij , thanks for your feedback. Could you add your request to this [thread](https://github.com/mixpanel/mixpanel-flutter/issues/36) instead?  I'm closing this one for now
