### ISSUE TITLE
Exclude bot traffic from Google & Apple tests

### ISSUE THREAD

**Issue by BghinC** [mixpanel/mixpanel-flutter#143]
I've submitted a new version of my app after implementing mixpanel.
However, I have received events coming from automated Play Store tests.
Is there a way to filter out those events before sending them to mixpanel? Even better if this can be implemented within the package directly.

<img width="500" alt="image" src="https://github.com/mixpanel/mixpanel-flutter/assets/43475742/e3c26f7d-3ed7-4ed6-9183-92534237a162">

**Comment by zihejia** [comment]
hi @BghinC , you can drop those events in Lexicon so they won't be ingested. For more help, you can reach out to our support.
