### ISSUE TITLE
Flutter web doesn't send events.

### ISSUE THREAD

**Issue by mihai-profiroiu-omnisourcetech** [mixpanel/mixpanel-flutter#144]
Hi,
I was integrating Mixpanel on our Flutter Application. I have setup as described on readme file, I tested with example application as well but I am not getting events from Flutter Web, however I can see the events from Android and iOS.
I have added  following code on web/index.html file.
  ```html
<head>
 <script src="./assets/packages/mixpanel_flutter/assets/mixpanel.js"></script>
</head>
  ```
Do I need to do something else other than this?

**Comment by k00na** [comment]
@mihai-profiroiu-omnisourcetech , how did you solve the issue?
