### ISSUE TITLE
Mixpanel doesnt work for Flutter web

### ISSUE THREAD

**Issue by k00na** [mixpanel/mixpanel-flutter#148]
Hey, thanks for this great library. 

It works well on mobile for me, but I'm having issues trying to make it work on Flutter web. 

My Flutter version is `3.22.2` and  `mixpanel_flutter: ^2.3.1`. Running `flutter doctor` returns everything as OK. 

Here's what I have in the code: 

1. I've added the bellow script in between `<head>` tags, as stated in docs: 

`<script src="./assets/packages/mixpanel_flutter/assets/mixpanel.js"></script>`

2. I successfully initialize Mixpanel in Dart code (as mentioned, Mixpanel works fine on mobile). 

But then I get this in the console: 

<img width="776" alt="Screenshot 2024-06-14 at 14 44 39" src="https://github.com/mixpanel/mixpanel-flutter/assets/13611208/d531ff60-833d-48cf-ac6b-8920f800173a">

Looks like it doesn't find the .js file at given URL. 

I've then manually added a JS variable `MIXPANEL_CUSTOM_LIB_URL`, which overrides the URL. 

```
<script type="application/javascript"> 
    var MIXPANEL_CUSTOM_LIB_URL = "https://cdn.jsdelivr.net/npm/mixpanel-browser@2.52.0/dist/mixpanel-jslib-snippet.min.js";
</script>
```

This removes the error but MixPanel still doesn't send events from Flutter web 🤷‍♂️ Any ideas what the issue could be or how to solve this? 

EDIT: I also tried changing Flutter version to `3.19.0` and mixpanel version to 2.0 and 2.2.0.

**Comment by kyleorin** [comment]
how'd you solve this?
