### ISSUE TITLE
Support for disabling IP address collection

### ISSUE THREAD

**Issue by brandon-bright** [mixpanel/mixpanel-flutter#15]
Unless I'm missing something the flutter sdk is missing the `useIPAddressForGeoLocation` variable that is present in the Android/iOS sdks.

Is there a workaround for disabling IP collection in flutter?

**Comment by zihejia** [comment]
hi @brandon-bright , we will be working on this. Thanks for bringing it up.

**Comment by zihejia** [comment]
Hi @brandon-bright , you can now use [setUseIpAddressForGeolocation](https://mixpanel.github.io/mixpanel-react-native/Mixpanel.html#setUseIpAddressForGeolocation) now, available in v1.2.0.
