### ISSUE TITLE
Error from building apk

### ISSUE THREAD

**Issue by EkramAminTornet** [mixpanel/mixpanel-flutter#155]
**Environment:**
- `mixpanel_flutter` version: 2.3.1
- Flutter version: 3.24.0

**Actual Behavior:**
The build fails with an error indicating that `android:attr/lStar` is missing.

**Additional Information:**
- The `android:attr/lStar` attribute was introduced in Android 12 (API level 31). Ensure that your `compileSdkVersion` and `targetSdkVersion` are set to 31 or higher in your `build.gradle` file.
- I have already tried updating dependencies and performing a clean build.

Thank you for your assistance!

![Screenshot 2024-08-17 at 12 41 59 AM](https://github.com/user-attachments/assets/2e7f1828-8e77-4a26-8827-8bb21e7b5035)

**Comment by zihejia** [comment]
Fixed in [v2.3.2](https://github.com/mixpanel/mixpanel-flutter/releases/tag/v2.3.2), thanks for bringing it up!
