### ISSUE TITLE
P0 : Update your compileSdkVersion to allow users who target compileSdkVersion 31+ to be able build the app with mixpanel-flutter 

### ISSUE THREAD

**Issue by nateshmbhat** [mixpanel/mixpanel-flutter#158]
Check this thread : https://github.com/flutter/flutter/issues/153281

you need to update your compileSdkVersion

**Comment by alexobviously** [comment]
@zihejia important

**Comment by zihejia** [comment]
Done. https://github.com/mixpanel/mixpanel-flutter/releases/tag/v2.3.2, thanks for bringing it up!
