### ISSUE TITLE
minSDK for Android

### ISSUE THREAD

**Issue by vlazdra** [mixpanel/mixpanel-flutter#164]
Hi @zihejia could you please update the Flutter SDK to mirror that of the underlaying Android SDK when it comes to releases and the breaking change of the minSDK for Android as discussed here: https://github.com/mixpanel/mixpanel-android/issues/843#issuecomment-2359051988

Thank you.

**Comment by jaredmixpanel** [comment]
Closed with https://github.com/mixpanel/mixpanel-flutter/pull/166
