### ISSUE TITLE
Boolean properties on iOS

### ISSUE THREAD

**Issue by rMozes** [mixpanel/mixpanel-flutter#20]
Hello,
I noticed that only on iOS if I use boolean properties then they are mapped to numbers on MP, so for example, if I set a bool property "is used: true" then on MP I see "is used: 1" from iOS

**Comment by zihejia** [comment]
hi @rMozes , thanks for bringing it up. It's been fixed in v1.2.1. https://github.com/mixpanel/mixpanel-flutter/releases/tag/v1.2.1
