### ISSUE TITLE
Migrate from JCenter

### ISSUE THREAD

**Issue by SoftWyer** [mixpanel/mixpanel-flutter#22]
[JCenter is End Of Life](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) and service availability has been flaky recently.

This project's use of JCenter in the Android gradle build files is causing our builds to fail. Can we remove it and use `mavenCentral` instead please.

**Comment by SoftWyer** [comment]
#24 

PR for change

**Comment by zihejia** [comment]
Thank you so much @SoftWyer ! It's been merged in [v1.3.0](https://github.com/mixpanel/mixpanel-flutter/releases/tag/v1.3.0). Closing this one now.
