### ISSUE TITLE
How to set User Properties via official plugin

### ISSUE THREAD

**Issue by Suryapratap-R** [mixpanel/mixpanel-flutter#25]
how to set user properties via official flutter plugin

**Comment by zihejia** [comment]
hi @Suryapratap-R , please refer to our doc [here ](https://developer.mixpanel.com/docs/flutter#storing-user-profiles). Hope that helps.

**Comment by tamoyal** [comment]
It's actually pretty unclear in the official docs because it says to not use `$` because those are reserved ...but do we prefix the reserved ones with `$` or not? I think it's ideal to have examples in the docs rather than explain this in words.
