### ISSUE TITLE
Can't write track_message to server

### ISSUE THREAD

**Issue by andre-paraense** [mixpanel/mixpanel-flutter#26]
I keep getting these exception messages on the output when running the Android app which has the lib integrated via Flutter. Does not happen with the iOS app.

E/MixpanelAPI.ViewCrawler(15446): Can't write track_message to server
E/MixpanelAPI.ViewCrawler(15446): com.mixpanel.android.viewcrawler.EditorConnection$EditorConnectionException
E/MixpanelAPI.ViewCrawler(15446): 	at com.mixpanel.android.viewcrawler.EditorConnection$WebSocketOutputStream.write(EditorConnection.java:143)
E/MixpanelAPI.ViewCrawler(15446): 	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
E/MixpanelAPI.ViewCrawler(15446): 	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
E/MixpanelAPI.ViewCrawler(15446): 	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
E/MixpanelAPI.ViewCrawler(15446): 	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
E/MixpanelAPI.ViewCrawler(15446): 	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
E/MixpanelAPI.ViewCrawler(15446): 	at android.util.JsonWriter.flush(JsonWriter.java:384)
E/MixpanelAPI.ViewCrawler(15446): 	at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.sendReportTrackToEditor(ViewCrawler.java:689)
E/MixpanelAPI.ViewCrawler(15446): 	at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.handleMessage(ViewCrawler.java:342)
E/MixpanelAPI.ViewCrawler(15446): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/MixpanelAPI.ViewCrawler(15446): 	at android.os.Looper.loop(Looper.java:223)
E/MixpanelAPI.ViewCrawler(15446): 	at android.os.HandlerThread.run(HandlerThread.java:67)
E/MixpanelAPI.ViewCrawler(15446): Can't close writer.
E/MixpanelAPI.ViewCrawler(15446): com.mixpanel.android.viewcrawler.EditorConnection$EditorConnectionException
E/MixpanelAPI.ViewCrawler(15446): 	at com.mixpanel.android.viewcrawler.EditorConnection$WebSocketOutputStream.close(EditorConnection.java:155)
E/MixpanelAPI.ViewCrawler(15446): 	at java.io.FilterOutputStream.close(FilterOutputStream.java:188)
E/MixpanelAPI.ViewCrawler(15446): 	at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:320)
E/MixpanelAPI.ViewCrawler(15446): 	at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:149)
E/MixpanelAPI.ViewCrawler(15446): 	at java.io.OutputStreamWriter.close(OutputStreamWriter.java:233)
E/MixpanelAPI.ViewCrawler(15446): 	at android.util.JsonWriter.close(JsonWriter.java:393)
E/MixpanelAPI.ViewCrawler(15446): 	at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.sendReportTrackToEditor(ViewCrawler.java:694)
E/MixpanelAPI.ViewCrawler(15446): 	at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.handleMessage(ViewCrawler.java:342)
E/MixpanelAPI.ViewCrawler(15446): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/MixpanelAPI.ViewCrawler(15446): 	at android.os.Looper.loop(Looper.java:223)
E/MixpanelAPI.ViewCrawler(15446): 	at android.os.HandlerThread.run(HandlerThread.java:67)
E/MixpanelAPI.ViewCrawler(15446): 	Suppressed: com.mixpanel.android.viewcrawler.EditorConnection$EditorConnectionException
E/MixpanelAPI.ViewCrawler(15446): 		at com.mixpanel.android.viewcrawler.EditorConnection$WebSocketOutputStream.write(EditorConnection.java:143)
E/MixpanelAPI.ViewCrawler(15446): 		at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
E/MixpanelAPI.ViewCrawler(15446): 		at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
E/MixpanelAPI.ViewCrawler(15446): 		at java.io.FilterOutputStream.close(FilterOutputStream.java:179)
E/MixpanelAPI.ViewCrawler(15446): 		... 9 more

$ flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/andre/Projetos/flutter
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/andre/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/andre/Library/Android
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • sdk gphone x86 (mobile)    • emulator-5554                        • android-x86    • Android 11 (API 30)
      (emulator)
    • iPhone 12 Pro Max (mobile) • 94D07846-2194-4BE7-8B28-B47BF4C2D56F • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      92.0.4515.159

**Comment by zihejia** [comment]
hi @andre-paraense , the error is from the A/B testing server and it might be due to the server/internet connection. If you don't use A/B Testing you can ignore this. We are deprecating the A/B testing feature and it will permanently be removed by the end of this year so you won't get this error anymore.

**Comment by andre-paraense** [comment]
> hi @andre-paraense , the error is from the A/B testing server and it might be due to the server/internet connection. If you don't use A/B Testing you can ignore this. We are deprecating the A/B testing feature and it will permanently be removed by the end of this year so you won't get this error anymore.

That's very good to know, thanks! 😊
