### ISSUE TITLE
Question: Do we support with addPushDeviceToken?

### ISSUE THREAD

**Issue by thomaslee-u** [mixpanel/mixpanel-flutter#3]
I have checked against the API over People class, there is no push device token support now

https://developer.mixpanel.com/docs/ios-push-notifications

Any plan to support ? 

Thanks

**Comment by zihejia** [comment]
hi @thomaslee-u , we are deprecating messages so sadly there is no plan to add it at the moment. But it's still available for iOS and Android until  January 1st, 2022.
