### ISSUE TITLE
iOS does not register super properties on `Mixpanel.init`

### ISSUE THREAD

**Issue by matthewshirley** [mixpanel/mixpanel-flutter#30]
`Mixpanel.init` takes an optional map of super properties to register. This argument is handled on Android by merging super and Mixpanel properties together and passing the merged map to the `getInstance` method. 

However, on iOS, the map is not merged, mostly likely because the mixpanel-swift `initialize` method does not handle any argument for super or Mixpanel properties:
https://github.com/mixpanel/mixpanel-swift/blob/master/Sources/Mixpanel.swift

It is expected that the `Mixpanel.init` has the same parity between platforms.
 
### Example Fix

```
        instance = Mixpanel.initialize(token: token!, instanceName: token!, optOutTrackingByDefault: optOutTrackingDefault ?? false)

        if superProperties != nil {
            let superAndMixpanelProperties = MixpanelTypeHandler.mixpanelProperties(properties: superProperties, mixpanelProperties: mixpanelProperties)
            instance?.registerSuperProperties(superAndMixpanelProperties)
        }
```

### Reference:

* https://github.com/mixpanel/mixpanel-flutter/blob/main/ios/Classes/SwiftMixpanelFlutterPlugin.swift#L150

* https://github.com/mixpanel/mixpanel-flutter/blob/main/android/src/main/java/com/mixpanel/mixpanel_flutter/MixpanelFlutterPlugin.java#L191

**Comment by zihejia** [comment]
Hi @matthewshirley , thanks for bringing it up. We have fixed it in v1.4.2. I'm closing this one now, pls feel free to reopen if the problem still exists.
