### ISSUE TITLE
Events are not shown in the dashboad for iOS

### ISSUE THREAD

**Issue by chintankotadia** [mixpanel/mixpanel-flutter#31]
We are facing a problem with events tracking for iOS Devices. Sometimes it is shown in the events dashboard and sometimes it does not. In Android devices, events are successfully getting tracked and shown in the dashboard immediately (After 60 seconds).

This happens with the example (https://github.com/mixpanel/mixpanel-flutter/tree/main/example) provided in the repository. In the debug logging mode, it gives a success response "Row inserted successfully in Mixpanel" but it does not show in the dashboard. 

iOS Version: 14.6, 14.7
iPhone 6s, 7, X and 12

Not sure, what am I missing over here?

Thanks!

**Comment by RobinLbt** [comment]
Encountering the same problem, did you find a solution @chintankotadia ?

**Comment by jgrandchavin** [comment]
Hello !

Do you find any solution to this issue ? I have the same

**Comment by jgrandchavin** [comment]
I downgrade to the version 1.3.0 and everything is ok on iOS and Android 👍

**Comment by RobinLbt** [comment]
Looks like it doesn't work on the simulator but works on a physical device (iOS only)

**Comment by zihejia** [comment]
hi @chintankotadia , there was a bug that prevent flush timer from firing in iOS and we have fixed it in v1.4.2. Sorry for the inconvenience. I'm closing this one now, please feel free to reopen if the problem still exists.
