### ISSUE TITLE
Email is undefined on Users dashboard

### ISSUE THREAD

**Issue by kkoken** [mixpanel/mixpanel-flutter#42]
Hi, fellow developers. We have encountered a problem with our mixpanel Users' dashboard. `Email` field is always shown as `undefined`

**Code implementation:**
```
 Future<void> setUserId() async {
    final userId = appUser.uuid!;
    await firebaseAnalytics.setUserId(userId);
    FirebaseCrashlytics.instance.setUserIdentifier(userId);

    mixpanel.identify(userId);
    mixpanel.getPeople().set("\$Email", appUser.email);

    mixpanel.registerSuperProperties({'isPremium': appUser.isPremium});
  }
```

<img width="750" alt="image" src="https://user-images.githubusercontent.com/87978754/146761055-f5a8b5da-43ee-47de-81d7-7f0882709a9d.png">

I have already checked the `appUser` properties and they are not null. Also, I tried with and without the `$` sign while sending `Email`, the result is the same. Can you collaborate with me to fix the issue? 
Many thanks.

**Flutter Doctor output:**
```
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.1 21C52 darwin-x64, locale en-TR)
    • Flutter version 2.8.0 at /Users/kaantahakoken/fvm/versions/2.8.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (12 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/kaantahakoken/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/kaantahakoken/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/kaantahakoken/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • Mi 9T (mobile) • c22e6ace • android-arm64  • Android 11 (API 30)
    • Chrome (web)   • chrome   • web-javascript • Google Chrome 96.0.4664.110
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)

• No issues found
```

**Comment by zihejia** [comment]
hi @kkoken , I see you're currently tracking an "Email" property but the "Email" column in the table is mapped to the Mixpanel managed "$email"(Not "$Email") property (with the $ in front). Since you're not tracking "$email" with the $, the "Email" column in the table is returning undefined. You can actually modify your table columns to show the "email" property you currently track(by clicking Edit Columns). Feel free to let me know if you have more questions.

**Comment by tomasbaran** [comment]
This is how I'm setting it: `MixpanelService.mixpanel?.getPeople().set('\$email', email);` and it shows correctly 
<img width="392" alt="Screenshot 2023-10-25 at 8 05 30 p m" src="https://github.com/mixpanel/mixpanel-flutter/assets/25743901/43d66a3d-54de-4cd7-94d3-fa98c0c69ab1">

but not in the dashboard:
<img width="667" alt="Screenshot 2023-10-25 at 8 06 06 p m" src="https://github.com/mixpanel/mixpanel-flutter/assets/25743901/88a491a5-a96b-4d71-bf7a-51602a04eab0">
