### ISSUE TITLE
Catch "Invalid argument" track parameter

### ISSUE THREAD

**Issue by tgpsantos** [mixpanel/mixpanel-flutter#47]
Hi,

When for some reason there's an invalid argument sent in the `parameters` to the `track()`method, I get a silent exception that is not being catched by crashlytics.

I tried wrapping the track method with a try-catch but it's not catching the exception, thus I believe it's being handled by Mixpanel somewhere in the java stack.

Is there anyway we, developers, can get access to exceptions in the mixpanel lib? We've just noticed a very serious problem happening in production in our app that was caused by an uncatched _invalid argument_ exception in the track method - and we didn't have a clue until we did an extensive troubleshoot and managed to replicate the same problem in debug.

**Comment by zihejia** [comment]
hi @tgpsantos , as a SDK for analytics, we should not crash the app for whatever reasons so we can't throw the exceptions. However you can turn on logging(`mixpanel.setLoggingEnabled(true);`) so Mixpanel will show more information about the exception. Let me know if you have any more questions. I'm closing this issue for now.
