### ISSUE TITLE
$app_version_string and $app_build_number properties are being set as the version of the SDK rather than the version of the app itself (iOS only)

### ISSUE THREAD

**Issue by arctouch-danielishara** [mixpanel/mixpanel-flutter#48]
Using version `1.4.2` of `mixpanel-flutter`.

Our current app version is set to `1.2.0` however we're seeing the App Version in Mixpanel set as `3.0.0`. It seems this may be mapped to the version of the underlying Swift SDK rather than the version of the app itself.

The same inconsistency is happening for the App Build Number.

This is only happening on iOS and not Android.

![Screen Shot 2022-01-17 at 10 39 52](https://user-images.githubusercontent.com/86305493/149779168-65bd6095-e26b-465c-8112-bc1535f61c60.png)

Obs: If it helps, a very similar issue was found and fixed on the `mixpanel-reactive-native` lib ([issue](https://github.com/mixpanel/mixpanel-react-native/issues/121))

**Comment by zihejia** [comment]
hi @arctouch-danielishara , we have fixed this issue in v1.4.3.  sorry for the inconvenience. Please feel free to reopen if the problem still exists.
