### ISSUE TITLE
Flutter web support

### ISSUE THREAD

**Issue by SylvainLosey** [mixpanel/mixpanel-flutter#5]
Is web support planned or should we use third party plugins if we need that functionality ?

**Comment by zihejia** [comment]
hi @SylvainLosey , thanks for bringing this up, we currently don't have a plan to support Flutter web yet but we will consider it in the future if there are more requests.

**Comment by allenzhou101** [comment]
Would love to have Flutter web!

**Comment by juliavi** [comment]
Please add web support, without it - flutter apps aren't truly cross-platform.

**Comment by BrightChad** [comment]
+1

**Comment by naiadelali** [comment]
+1

**Comment by doppio** [comment]
+1! If the package isn't going to support web, please say so in the README. I spent my evening learning about Mixpanel and adding it to my Flutter web project, only to find that that package is not truly cross-platform. :(

**Comment by ozz-rjq** [comment]
+1

**Comment by zihejia** [comment]
Thank you all for the feedback! I will add the flutter web support soon.

**Comment by calmh** [comment]
Glad to hear it, it's important. :) (subscribing to issue)

**Comment by zihejia** [comment]
hi Guys, we have added the Flutter Web support in 1.4.0. I'm closing this issue now, feel free to let me know if there is any issue. Again, thank you for choosing Mixpanel!
