### ISSUE TITLE
Unable to wait for reset before registering new super properties

### ISSUE THREAD

**Issue by alexpdraper** [mixpanel/mixpanel-flutter#50]
We want to register some generic super properties whenever a user signs out, so we’ve got some code that looks like this…

```dart
mixpanel.reset();
mixpanel.registerSuperProperties(…);
```

But it doesn’t work! The reset happens asynchronously and deletes the super properties we registered. Note that this seems to be a regression that came with the migration to Mixpanel-Swift v3. The problem doesn’t seem to happen on Android.

**Comment by zihejia** [comment]
hi @alexpdraper , thanks for bringing this up. We will address this issue.

**Comment by zihejia** [comment]
hi @alexpdraper,  it has been fixed in [v1.4.5](https://github.com/mixpanel/mixpanel-flutter/releases/tag/v1.4.5). We fixed it in the iOS SDK then v1.4.5 includes the update. I'm closing this one now, please feel free to reopen if the problem still exists.
