### ISSUE TITLE
Registering non-string super props in init fails

### ISSUE THREAD

**Issue by alexpdraper** [mixpanel/mixpanel-flutter#51]
As the title suggests, the `Mixpanel.init` method doesn’t register super props with non-string values. I’m not a swift know-er, but I think the culprit is [this line here](https://github.com/mixpanel/mixpanel-flutter/blob/main/ios/Classes/SwiftMixpanelFlutterPlugin.swift#L152). I believe the typing should be `[String: Any]` instead of `[String: String]`.

**Comment by zihejia** [comment]
hi @alexpdraper , it has been fixed in [v1.4.5](https://github.com/mixpanel/mixpanel-flutter/releases/tag/v1.4.5). Thanks for bringing it up! I'm closing this one now, please feel free to reopen if the problem still exists.
