### ISSUE TITLE
How to set user name, email & other details ?

### ISSUE THREAD

**Issue by SaravanarajaGITHUB** [mixpanel/mixpanel-flutter#53]
![image](https://user-images.githubusercontent.com/6235704/152180657-c0ca3bbd-47ae-474b-851c-836a9bb7683a.png)

Through identity "mixpanel.identify("13791");" we can create a user how to add name, email & other properties which marked in the screen shot

**Comment by doppio** [comment]
Looks like you can call `mixpanel.getPeople.set(propertyName, value)`

**Comment by SaravanarajaGITHUB** [comment]
> Looks like you can call `mixpanel.getPeople().set(propertyName, value)`

Thanks for the syntax I came through this same syntax in the documentation, what the exact syntax to change the property for,

- Email
- Updated at
- CountryCode
- Region
- City

I tried to set it like this 

`trackAnalytics.getPeople().set("Name", _userUseCase.getEmployeeName());
 trackAnalytics.getPeople().set("Email", _userUseCase.getEmployeeEmail());`

these properties are added but it's not reflected in the column list item for each user. how to change that?

**Comment by doppio** [comment]
Use $name and $email as the property names. This document has a full list of the reserved property names:
https://help.mixpanel.com/hc/en-us/articles/115004708186-What-is-the-difference-between-Event-Properties-Super-Properties-and-People-Properties-and-which-should-I-use-

**Comment by SaravanarajaGITHUB** [comment]
> Use $name and $email as the property names. This document has a full list of the reserved property names: https://help.mixpanel.com/hc/en-us/articles/115004708186-What-is-the-difference-between-Event-Properties-Super-Properties-and-People-Properties-and-which-should-I-use-

Hi Bud saw this doc too, this is the error I got when I tried using the dollar symbol, see the image below

![image](https://user-images.githubusercontent.com/6235704/153058791-726a0eaf-fb22-460e-aa13-d49721b2ec7e.png)

It forces me to create a variable for email & that is not wrong with flutter because that is how it works, so what's the proper syntax for it, what I'm missing.

**Comment by SaravanarajaGITHUB** [comment]
![image](https://user-images.githubusercontent.com/6235704/153060272-e2c2e168-5299-4daf-b8f3-31902d0df167.png)

`trackAnalytics.getPeople().set("Email", _userUseCase.getEmployeeEmail());`

through this above code, the addition email property is added to the user but not the default email, from the edit column option I made my added email to visible you can see that in the pic, but I want the use the default email property which I marked in the blue circle.

 In the doc, it denotes we have to use $ symbol, but I'm not sure how to use.

**Comment by doppio** [comment]
Dart's "string interpolation" thinks you're trying to use the `$` to insert a variable called `Email` there. You can use a `\` to escape the dollar sign: `trackAnalytics.getPeople().set("\$email", _userUseCase.getEmployeeEmail());`

**Comment by SaravanarajaGITHUB** [comment]
> Dart's "string interpolation" thinks you're trying to use the `$` to insert a variable called `Email` there. You can use a `\` to escape the dollar sign, to tell Dart that it's just part of the text: `trackAnalytics.getPeople().set("\$email", _userUseCase.getEmployeeEmail());`

Thanks for the syntax this is what I'm searching for, thanks for your time.
