### ISSUE TITLE
People.identify is not exposed

### ISSUE THREAD

**Issue by doppio** [mixpanel/mixpanel-flutter#56]
https://developer.mixpanel.com/docs/android#identify
The Mixpanel documentation states:

> To assign your own distinct_ids, you can use [MixpanelAPI.identify](http://mixpanel.github.io/mixpanel-android/com/mixpanel/android/mpmetrics/MixpanelAPI.html#identify-java.lang.String-) and [MixpanelAPI.getPeople().identify](http://mixpanel.github.io/mixpanel-android/com/mixpanel/android/mpmetrics/MixpanelAPI.People.html#identify-java.lang.String-). **We strongly recommend using the same distinct id for both calls.**

It looks like People.identify() is not exposed in the Flutter package. Is there some way to accomplish this?

**Comment by zihejia** [comment]
Hi @doppio , for Flutter, `identify` will call `People.identify()` behind the scenes in Android. So you don't have to worry about it.

**Comment by doppio** [comment]
Great! Is this also the case in iOS @zihejia?
