### ISSUE TITLE
getDistinctId() returns a future that can resolve to null

### ISSUE THREAD

**Issue by santiracca** [mixpanel/mixpanel-flutter#67]
The method getDistinctId() has a return type of `Future<String?>`.

This implies that it is possible to have a null distinct id, however the documentation and examples state that a string is always returned.

Is is possible to have a null id returned from the method or is the return type not proper for this method.

**Comment by jaredmixpanel** [comment]
@santiracca this has been updated in v1.5.0, `getDistinctId()` now has return type `Future<String>`
