### ISSUE TITLE
Support the import endpoint?

### ISSUE THREAD

**Issue by brbatwork** [mixpanel/mixpanel-flutter#68]
Have a general question, that I couldn't find an answer to in the source.  Does this plugin support the [`/import` endpoint](https://help.mixpanel.com/hc/en-us/articles/115004734463) to handle events that are older than 5 days old while the device was offline?  I couldn't find a reference to `/import` in the code, or in the [java MixPanelAPI](https://github.com/mixpanel/mixpanel-java/blob/7256bebe5faa462efbfe92d9b0dd22e9fadded02/src/main/java/com/mixpanel/mixpanelapi/MixpanelAPI.java#L41) file

**Comment by jaredmixpanel** [comment]
Hi @brbatwork, no the `/import` endpoint is not currently supported by the Flutter SDK, nor the underlying native SDKs.
