### ISSUE TITLE
Null safety migration

### ISSUE THREAD

**Issue by incendial** [mixpanel/mixpanel-flutter#7]
@zihejia hi, with recent dart 2.12 and flutter 2.0 releases are there any plans for migration to null safety?
I'd be happy to open a PR for null safety if it isn't already in the works.

**Comment by zihejia** [comment]
hi @incendial , we don't have a plan to support it for now, but you are more than welcome to open a PR. Thank you!

**Comment by incendial** [comment]
@zihejia great, created a PR #9, could you please take a look?

**Comment by incendial** [comment]
@zihejia hi, sorry for pinging, but are there any chances that you will take a look at the PR?

**Comment by zihejia** [comment]
hi @incendial thank you so much for the PR, we will take a look by this week.

**Comment by zihejia** [comment]
Hi @incendial, 1.1.0 has released and it has null safety support, thanks again! https://pub.dev/packages/mixpanel_flutter
