### ISSUE TITLE
[web] mixpanel_flutter for web doesn't implement 'setServerURL'

### ISSUE THREAD

**Issue by tgpsantos** [mixpanel/mixpanel-flutter#70]
Hey Guys,

We've a mobile app and will now make it a web app. We are using mixpanel flawlessly both in iOS and android using this package.

Our mixpanel project is in europe thus we need to call `    _mixpanel.setServerURL('https://api-eu.mixpanel.com'); `. Is this something you could easily solve? 

Thanks in advance!

**Comment by sydneyagcaoili** [comment]
Same problem here

**Comment by jaredmixpanel** [comment]
@tgpsantos @sydneyagcaoili @hamirshekhawat this is fixed in v1.5.0

**Comment by tgpsantos** [comment]
Thanks a bunch, @jaredmixpanel! 

Btw, I noticed `flush()` is not implemented for web as well, so I went ahead and created a [new issue](https://github.com/mixpanel/mixpanel-flutter/issues/76))
