### ISSUE TITLE
App session event

### ISSUE THREAD

**Issue by brenoasm** [mixpanel/mixpanel-flutter#71]
Hello, I would like to ask if there is some known error regarding the App Session event. Our dashboards showed us that we had a really hard drop on those events and we did nothing within our app. Testing now, I see that App Session is never sent. Thanks in advance.

We are using version 1.4.5. Already tried to upgrade and downgrade, nothing has changed.

**Comment by zihejia** [comment]
hi @brenoasm , which platform(iOS/Android) are you having the problem with?

**Comment by simplenotezy** [comment]
I am curious about this too. We migrated from Amplitude, and there the library automatically sets session events. However, it appears that these events need to be sent manually in Mixpanel, could that be true? https://docs.mixpanel.com/docs/analysis/advanced/sessions#how-sessions-work
