### ISSUE TITLE
Mixpanel track event > track(String, Map<String, dynamic>) function have issue. Kindly correct it. Added the solution.

### ISSUE THREAD

**Issue by akshayindia** [mixpanel/mixpanel-flutter#72]
Hi Mixpanel Team,

instead of this 
void track(String eventName, {Map<String, dynamic>?} properties) {

it should be function - 
void track(String eventName, Map<String, dynamic>? properties) {

I've attached the screenshot and changed it in my project. please do change the plugin as well. 

<img width="1040" alt="Screenshot 2022-04-25 at 5 32 29 PM" src="https://user-images.githubusercontent.com/36562389/165085341-fa3e8d53-4422-45e3-a78f-3b01264add9a.png">

**Comment by hamirshekhawat** [comment]
Why do you want the named parameter to be removed?

**Comment by jaredmixpanel** [comment]
@akshayindia the `properties` argument is optional, the `{ }` indicate that.

**Comment by akshayindia** [comment]
Hi @jaredmixpanel,

Thanks for the comment. 

Then there is a little error to make it optional you have to put the named parameter in the {} bracket.
correct > {Map<String, dynamic>? properties} 
wrong > {Map<String, dynamic>?} properties
or if you want to make it positional then in square bracket [].

Kindly make the changes.
document for ref - https://medium.com/jay-tillu/optional-arguments-in-dart-9114152a0da3

Looking forward to it.

**Comment by akshayindia** [comment]
> Why do you want the named parameter to be removed?

I don't want to remove the named parameter, I want to correct it, or make it optional as the code is having errors while debugging or make it non-optional. 

I got this error in Mixpanel SDK - 1.4.5

**Comment by jaredmixpanel** [comment]
@akshayindia I do not see the error you're describing: https://github.com/mixpanel/mixpanel-flutter/blob/main/lib/mixpanel_flutter.dart#L177

**Comment by hamirshekhawat** [comment]
@akshayindia I think you should add mixpanel to a fresh project and check the code again for version 1.4.5. The mistake you are mentioning doesn't exist. If you are getting errors, you must've done some changes directly to the source in pub-cache code. It is recommended not to edit that code.
For your reference please check this in git history for version 1.4.5 - https://github.com/mixpanel/mixpanel-flutter/blob/48d5f7ad0a2ac83da31b27bc2ed0637fbd4046ca/lib/mixpanel_flutter.dart#L173
For future reference, confirm the error by cloning the library and checking history, match with your error and then create an issue.

**Comment by akshayindia** [comment]
Yup, in the git history folder, it is showing correct.


Sorry about this.

Thanks for sharing the reference.
