### ISSUE TITLE
Bad response from MixpanelAPI

### ISSUE THREAD

**Issue by YanPolt** [mixpanel/mixpanel-flutter#94]
I get the following log: response was {"error":null,"status":1} (Thread 289)
I am using mixpanel 2.0.0 and Flutter 3.3.5.

**Comment by phalox** [comment]
Can confirm on Android emulator and IoS that both are not displaying any events. When downgrading to v 1.6.0, I get events again.

**Comment by phalox** [comment]
Tried the downgrade on ios, doesn't work...

At its core, it's just doing an HTTP call.... I don't understand why only we're experiencing this issue.

**Comment by zihejia** [comment]
hi @phalox , sorry for the late response. If you don't see events, first make sure the simulator has access to the internet. Then please follow the faq: https://github.com/mixpanel/mixpanel-flutter#faq "Why aren't my events showing up?"

**Comment by blakehawkins** [comment]
{"error":null,"status":1} is a *success* response as descirbed in the API docs: https://developer.mixpanel.com/reference/track-event
