### ISSUE TITLE
Default user properties not available for new profiles?

### ISSUE THREAD

**Issue by kimdhoe** [mixpanel/mixpanel-flutter#96]
### Expected behavior

We want to know default profile properties such as _Country Code_, _Region_, and _City_ for each user.

### Actual behavior

Some profile properties are not available for new profiles at first. For instance, _Country Code_, _Region_, and _City_ are `undefined` at first when we only called `Mixpanel.identify()` with a user ID. Instead, they becomes available once we update the profile using `Mixpanel.getPeople().set()` method.

<img width="895" alt="Screen Shot 2023-01-10 at 3 37 49 PM" src="https://user-images.githubusercontent.com/10362796/211482762-b966144e-ba47-4af2-8117-de73b5725dda.png">

I was wondering if the library supposed to work this way or we're missing something.  Is this a normal behavior or a bug?

**Comment by catliaw** [comment]
Hi @kimdhoe , can you send a support ticket to support@mixpanel.com? Please reference this issue and provide the link to the Users report where you are seeing user profiles without the default profile properties. For context, the default profile properties only get set for a profile when you set a profile property (use Mixpanel.getPeople().set() method), which creates a "profile". The behavior that you mentioned is expected. Before then, this user is either an anonymous user who hasn't authenticated, for which identify() was not yet called. Or they simply did not have any profile properties set yet. Would be happy to confirm for you in a support ticket.

**Comment by kimdhoe** [comment]
Thanks for the reply, @catliaw. Everything is clear now so no need to send a support ticket.
We recently migrated to mixpanel-flutter in the process of removing Segment from our codebase. This was unseen behavior so I was wondering if it was expected or not.
